### ISSUE TITLE
Image order gets changed if urls and files are mixed in input parameter 

### ISSUE THREAD

**Issue by lukacoufyl** [theirix/ptpimg-uploader#5]
example :
$ ptpimg_uploader -k <my_api_key> --nobell https://m.media-amazon.com/images/M/MV5BNGY0NzgzYzctYWQwMC00MzM2LThjNGMtZjFjMWUyNzg0ZmM0XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UY864_.jpg army1.png army2.png https://m.media-amazon.com/images/M/MV5BNDlmMjJkMjAtODc3OS00NjhhLTgyOTktNzFmYTZkN2FlNjkzXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_FMjpg_UX400_.jpg yvon1.png yvon2.png

the expected order :
army_poster.jpg
army1.png
army2.png
yvon_poster.jpg
yvon1.png
yvon2.png

but the output:
https://ptpimg.me/1vipvz.png    #army1.png
https://ptpimg.me/mbbudw.png    #army2.png
https://ptpimg.me/02s1z6.png    #yvon1.png
https://ptpimg.me/dj58b7.png    #yvon2.png
https://ptpimg.me/k51i56.jpg    #army_poster.jpg
https://ptpimg.me/u2hr97.jpg    #yvon_poster.jpg

in the current code, the file and url upload is partitioned and file uploads take precedence. so the order gets changed if mixed with urls and files.

**Comment by lukacoufyl** [comment]
pull request fixing this issue : https://github.com/theirix/ptpimg-uploader/pull/6

**Comment by theirix** [comment]
Thank you for the PR! Confirming it works with a mixed order.

Refactored a little, added redownloading remote file and published a new version 0.6.

**Comment by lukacoufyl** [comment]
> Refactored a little, added redownloading remote file and published a new version 0.6.

hi, i am actually new with the use of requests. so bear with me please. could you explain on the advantages of redownloading remote files when adding from url? and if i do it from direct urls like i tried what potential errors i may face? 
thank you

**Comment by theirix** [comment]
Sure! It was not related to the requests library. It was a workaround for a bug in ptpimg server. At first, I used `link-upload` POST parameter that contains a direct URL to the image. No actual image was sent. Then the ptpimg server downloads the image by itself and saves it. Fast and easy.

But if an URL has special symbols (as I recall it was hash or brace), the server could not process this URL. So in #2 I introduced downloading an image locally and sending it to the ptpimg as it was a local file. Maybe this bug is gone but I prefer to keep this behaviour to be sure
